# Generated by Django 4.2.29 on 2026-04-05 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='costomerAddress',
            new_name='customerAddress',
        ),
    ]
