# Generated by Django 4.2.29 on 2026-04-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_promocode_order_bonusawarded_order_discountamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='spentBonus',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
